version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: .dockerfiles/BackendDev
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/opt/app
    restart: always
  backend_test:
    build:
      context: ./
      dockerfile: .dockerfiles/BackendDev
    command: yarn run test:watch
    ports:
      - "9005:9005"
    volumes:
      - ./backend:/opt/app
    restart: always

